### ISSUE TITLE
func GetTimes returns everything in CST

### ISSUE THREAD

**Issue by RichDavis1** [sixdouglas/suncalc#6] opened 2020-11-25 23:52 UTC
Every item in the map gets returned in CST, I couldn't find anything in the docs on if this is intended/how to reformat. It's no big deal if not but if there is a way to somehow designate the LoadLocation that would be helpful. 

This is a helpful lib btw, thanks for this.

**Comment by RichDavis1** [comment] 2020-11-26 00:05
Closing as I'm a dingus, it automatically uses the timezone of the coordinates.

**Comment by RichDavis1** [comment] 2020-12-15 00:05
I tried this again on coordinates in PST and it is still returning CST times. Is this intended?

**Comment by sixdouglas** [comment] 2020-12-15 23:00
Hi @RichDavis1 can you send the simplest possible code to reproduce this issue?

I have an oncoming PR waiting to be merged with some Unit Tests. You can probably use them as starting point.
PS: I haven't merged it yet since it contains some breaking changes, and I didn't take the time for a deep dive into creating a new module version yet. Let me know if this version looks good for you and would suit you better.

**Comment by sixdouglas** [comment] 2024-02-14 22:39
No answers for over 2 years

**Closed as completed by sixdouglas** 2024-02-14 22:39 UTC
